### ISSUE TITLE
A way to monitor large storages

### ISSUE THREAD

**Issue by arnokeesman** [Mineduino/Mineduino-spigot#12]
With farms that require a lot of chests for storage having some kind of group for the chests would be great to just get the amount of items.

Example output:
```JSON
[{"material":"white_wool","amount":672},{"material":"pink_wool","amount":12},{"material":"light_grey_wool","amount":534}]
```

**Comment by Razikus** [comment]
Implemented in ee2e587b5bc40800d73134fddaa4af978e5aa4f6
